# the compiler
CC = sac2c

# compiler flags:
CFLAGS  = -ecc -check tc

# the build target executable:
TARGET = week1

all:
	$(CC) $(CFLAGS) -o ./$(TARGET) $(TARGET).sac

clean:
	$(RM) $(TARGET).c
	$(RM) $(TARGET)
